services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"      # Apache web server
      - "8080:8080"    # Laravel Reverb WebSocket server
    volumes:
      - ./storage:/var/www/html/storage
      - ./database:/var/www/html/database
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
    restart: unless-stopped
    container_name: festvalley-app
