services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"      # Apache web server
      - "8080:8080"    # Laravel Reverb WebSocket server
    volumes:
      # Mount source code for development (hot reload)
      - .:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/var/www/html/database/database.sqlite
      - REVERB_HOST=0.0.0.0
      - REVERB_PORT=8080
    restart: unless-stopped
    container_name: festvalley-dev
