name: Deploy to Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run Deployment Script
        run: |
          sshpass -p "${{ secrets.SSH_PASSWORD }}" ssh -o StrictHostKeyChecking=no root@192.168.192.101 << 'EOF'
            cd /www/wwwroot/bandgeeks.local
            git fetch origin dev
            git reset --hard origin/dev
            composer dump-autoload
            php artisan migrate --force
            php artisan optimize:clear
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          EOF
